### PR TITLE
[RSDK-2215] remove old api endpoints

### PR DESCRIPTION
**Pull request by JohnN193**
removes old api endpoints from the orbslam repo. This will not be merged until after [rdk removal](https://viam.atlassian.net/browse/RSDK-2242?atlOrigin=eyJpIjoiZGZhM2NiMzMyM2M3NGJiZTk3MjY2NTQ0ZGJiZjgyNzEiLCJwIjoiaiJ9) is [merged](https://github.com/viamrobotics/rdk/pull/2014) but should not be blocked

ticket: https://viam.atlassian.net/browse/RSDK-2242

### CODE REVIEW

**Review by tessavitabile — APPROVED** [review]
I think you can also remove ProcessDataForTesting, which I created to test the jpeg map representation.

**Review by jeremyrhyde — COMMENTED** [review]
LGTM, love the code deletion

**Review by jeremyrhyde — APPROVED** [review]
LGTM

**Review by nicksanford — APPROVED** [review]
LGTM

**Review by nicksanford — APPROVED** [review]

**Pull request merged**
